[project]
name = "github"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.12"
dependencies = [
    "fastmcp[standard]>=2.12.5",
]

[dependency-groups]
dev = [
    "ruff>=0.14.1",
]
